# Generated by Django 5.0.3 on 2024-03-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('print_time', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/boxes')),
            ],
        ),
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('price_per_kg', models.FloatField()),
                ('image', models.ImageField(upload_to='images/filaments')),
            ],
        ),
    ]
